import type { Expedition } from "../types";

/**
 * The operator's expeditions — ported from the wireframe dataset, kept
 * internally consistent. Each references its field leader (Person) and route
 * by id. `route-<id>` routes are created by the route generator.
 */
export const EXPEDITIONS: readonly Expedition[] = [
  {
    id: "tdp",
    name: "Torres del Paine Circuit",
    region: "Patagonia",
    country: "Chile",
    coordinates: { lat: -50.94, lng: -73.41 },
    coordsLabel: "-50.94°, -73.41°",
    leaderId: "mara-restrepo",
    status: "in-field",
    statusLabel: "In field",
    statusTone: "danger",
    capacity: 14,
    filled: 14,
    dayCurrent: 4,
    dayTotal: 8,
    departLabel: "May 31",
    readiness: 94,
    grade: "strenuous",
    distanceKm: 128,
    gainM: 6240,
    map: { x: 24, y: 48 },
    routeId: "route-tdp",
  },
  {
    id: "anp",
    name: "Annapurna Sanctuary Trek",
    region: "Gandaki",
    country: "Nepal",
    coordinates: { lat: 28.53, lng: 83.88 },
    coordsLabel: "28.53°, 83.88°",
    leaderId: "lhakpa-tamang",
    status: "in-field",
    statusLabel: "In field",
    statusTone: "ok",
    capacity: 12,
    filled: 11,
    dayCurrent: 2,
    dayTotal: 11,
    departLabel: "Jun 01",
    readiness: 88,
    grade: "strenuous",
    distanceKm: 115,
    gainM: 5180,
    map: { x: 62, y: 60 },
    routeId: "route-anp",
  },
  {
    id: "wrh",
    name: "Wind River High Route",
    region: "Wyoming",
    country: "United States",
    coordinates: { lat: 43.1, lng: -109.62 },
    coordsLabel: "43.10°, -109.62°",
    leaderId: "dele-okafor",
    status: "departing",
    statusLabel: "Departing",
    statusTone: "warn",
    capacity: 10,
    filled: 9,
    dayCurrent: 0,
    dayTotal: 9,
    departLabel: "Jun 05",
    readiness: 61,
    grade: "expert",
    distanceKm: 130,
    gainM: 8900,
    map: { x: 47, y: 30 },
    routeId: "route-wrh",
  },
  {
    id: "kun",
    name: "Kungsleden Traverse",
    region: "Lapland",
    country: "Sweden",
    coordinates: { lat: 68.36, lng: 18.78 },
    coordsLabel: "68.36°, 18.78°",
    leaderId: "anja-lindqvist",
    status: "planning",
    statusLabel: "Planning",
    statusTone: "slate",
    capacity: 12,
    filled: 6,
    dayCurrent: 0,
    dayTotal: 7,
    departLabel: "Jun 22",
    readiness: 42,
    grade: "moderate",
    distanceKm: 105,
    gainM: 2100,
    map: { x: 78, y: 36 },
    routeId: "route-kun",
  },
  {
    id: "dol",
    name: "Dolomites Alta Via 1",
    region: "Veneto",
    country: "Italy",
    coordinates: { lat: 46.62, lng: 12.05 },
    coordsLabel: "46.62°, 12.05°",
    leaderId: "salvo-conti",
    status: "planning",
    statusLabel: "Planning",
    statusTone: "slate",
    capacity: 16,
    filled: 12,
    dayCurrent: 0,
    dayTotal: 10,
    departLabel: "Jun 29",
    readiness: 55,
    grade: "moderate",
    distanceKm: 120,
    gainM: 6800,
    map: { x: 33, y: 74 },
    routeId: "route-dol",
  },
  {
    id: "sky",
    name: "Skye Cuillin Ridge",
    region: "Hebrides",
    country: "Scotland",
    coordinates: { lat: 57.2, lng: -6.22 },
    coordsLabel: "57.20°, -6.22°",
    leaderId: "iona-mackay",
    status: "complete",
    statusLabel: "Complete",
    statusTone: "idle",
    capacity: 8,
    filled: 8,
    dayCurrent: 5,
    dayTotal: 5,
    departLabel: "May 18",
    readiness: 100,
    grade: "expert",
    distanceKm: 40,
    gainM: 3400,
    map: { x: 40, y: 18 },
    routeId: "route-sky",
  },
] as const;
